---
name: nativefier

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        arch:
          - x64
          - arm64
        os:
          - linux
          - darwin
          - windows

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: |
          npm i -g nativefier

      - if: ${{ matrix.os == 'windows' }}
        run: |
          apt-get update
          apt-get -y install wine64

      - run: make build ARCH=${{ matrix.arch }} OS=${{ matrix.os }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: |
            Sphere-*
